# Site settings
title: Dancing Larva Blog
email: dancing.larva@Gmail.com
baseurl: ""# the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Sidebar settings
description: The prepared person has the future.

# Social icons
facebook: username
linkedin: username
github: username
deviantart: username
codepen: username

footer: 개발이 좋다

# Build settings
markdown: kramdown
